// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuanLy.Infrastructure.Context;

#nullable disable

namespace QuanLy.Infrastructure.Migrations
{
    [DbContext(typeof(DASContext))]
    [Migration("20260402092715_Auth_User")]
    partial class Auth_User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_Assign", b =>
                {
                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.Property<int>("ObjectID")
                        .HasColumnType("integer");

                    b.HasKey("Permission");

                    b.ToTable("Auth_Assign");
                });

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_Assign_role", b =>
                {
                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.Property<int>("ObjectID")
                        .HasColumnType("integer");

                    b.HasKey("Permission");

                    b.ToTable("Auth_Assign_role");
                });

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_Permissions", b =>
                {
                    b.Property<string>("Permission")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Permission");

                    b.ToTable("Auth_Permissions");
                });

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<byte>("IsShow")
                        .HasColumnType("smallint");

                    b.Property<byte>("IsSysAdmin")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("RoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_UserRoles", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<int>("RoleID")
                        .HasColumnType("integer");

                    b.HasKey("UserID");

                    b.ToTable("Auth_UserRoles");
                });

            modelBuilder.Entity("QuanLy.Domain.Models.Auth_Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<byte>("Active")
                        .HasColumnType("smallint");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<byte>("IsShow")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsereName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("ID");

                    b.ToTable("Auth_Users");
                });
#pragma warning restore 612, 618
        }
    }
}
